### ISSUE TITLE
Camera not turning on (even when allowed/enabled in settings) during the test when using MacOS.

### ISSUE THREAD

**Issue by MelusiZondi** [SafeExamBrowser/seb-mac#432]
> [!IMPORTANT]
> - Please _always_ consult the documentation first before creating a bug report: https://safeexambrowser.org/windows/win_usermanual_en.html.
> - Please _always_ attach the log file(s) of the affected session(s)! They can be found under `%LocalAppData%\SafeExamBrowser\Logs`.
Kindly give instruction on how to get the log files on MacOS devices so we can instruct our students to send these to  us so we can forwards to you for further investigation.

**Describe the Bug**
Safe Exam Browser giving a prompt to allow camera access (on MacOS devices), even after the the user has Allowed webcam access. This is happening during the test. (screenshot attached). 

**Steps to Reproduce**

**Expected Behavior**
Safe Exam Browser should start the Webcam and periodically take screenshots as the student is attempting the test on LMS (Moodle)

**Screenshots**
![image](https://github.com/user-attachments/assets/a7c19381-c290-4a29-aac1-b0f69d339b0a)

**Version Information**
 - MacOS Sonoma, Version 14 
 - SEB-Version 3.3.3

**Additional Context**
This error is recurring across all out students who use MacOS devices (Especially using MacOS 14 and above), non of them are able to complete the Mock Test we created in order to ensure that SEB works properly for all our students before our official assessments begin.

**Comment by danschlet** [comment]
Try it with the 3.4 beta version, there the issue should be fixed: https://github.com/SafeExamBrowser/seb-mac/releases

The target is to have a final release of 3.4 for macOS next week.

**Comment by MelusiZondi** [comment]
Hi Daniel,

Thank you for your quick response, we will share this with our students who use the MacOS devices.

Regards

________________________________

**Comment by danschlet** [comment]
@MelusiZondi did the 3.4 update fix the issue for your students?

**Comment by MelusiZondi** [comment]
Hi Daniel,

Please note that we will test it today and revert back to you with feedback. The Beta version that was out at the time did not resolve the issue though, hopefully the full version will do the trick.

Regards

________________________________

**Comment by aldadelas** [comment]
@danschlet I'm using macOS sequoia 15.1.1, it still error. I'm a user that have to take an technical test using safe exam browser. Any solution ? eventhough i'm install v3.4.1 or 3.5 beta, it still the same error.

**Comment by danschlet** [comment]
@aldadelas they probably didn't use correct settings for macOS. SEB for macOS requires to explicitly allow camera and microphone access in its settings. If they just configured and tested it with SEB for Windows, they won't realize that it wouldn't work on Mac. So tell your exam provider about the issue you have.

**Comment by danschlet** [comment]
Study the information here properly, then you can make it work.

There is neither a macOS version 18.5 nor an SEB 3.9 for macOS or iOS...

**Comment by 1Mohamed1Ahmed1** [comment]
<img width="1600" height="1200" alt="Image" src="https://github.com/user-attachments/assets/48df9bff-cdf9-4b3c-b0ae-3bbeadf1ddd3" />

<img width="701" height="521" alt="Image" src="https://github.com/user-attachments/assets/84103274-ac21-40bc-a816-c371780a3113" />

<img width="718" height="557" alt="Image" src="https://github.com/user-attachments/assets/fa4e7131-c0d2-4ed5-a50e-7c61104c0ee5" />

Device: MacBook Air M1 (Apple Silicon)
Operating System: macOS Tahoe 26.5.1
Safe Exam Browser Version: 3.6.1
When I launch my exam in Safe Exam Browser, the camera preview appears completely black and the exam page displays a message asking me to allow camera access.

However, I have already granted all required permissions to Safe Exam Browser:

Camera access: Enabled
Screen & System Audio Recording: Enabled

I have verified these permissions in macOS Privacy & Security settings.

Troubleshooting Steps Already Performed
Restarted the MacBook.
Restarted Safe Exam Browser.
Removed and re-granted camera permissions.
Verified that the camera works correctly in other applications.
Tested the camera in FaceTime (works normally).
Tested the camera in Photo Booth (works normally).
Confirmed that Safe Exam Browser appears in the Camera permissions list and is enabled.
Confirmed that Safe Exam Browser appears in Screen Recording permissions and is enabled.
Current Behavior
The camera works normally outside Safe Exam Browser.
Inside Safe Exam Browser, the camera preview remains black.
The exam platform displays a message indicating that camera access is not available or not allowed.

Could you please help me determine whether this is:

A compatibility issue between Safe Exam Browser 3.6.1 and macOS Tahoe 26.5.1,
A WebRTC/camera permission issue inside SEB,
Or an issue with the exam platform configuration?

I have attached screenshots showing the permissions and the error message.

Thank you for your assistance.

Best regards

**Comment by danschlet** [comment]
See https://github.com/SafeExamBrowser/seb-mac/issues/538.

**Comment by 1Mohamed1Ahmed1** [comment]
i do it and still the same

**Comment by hagaralaa-55** [comment]
@1Mohamed1Ahmed1 Iam facing same issue with DEPI exam platform , did u find a solution for that ?? it will be great if u can share it with me 
thnx.

**Comment by 1Mohamed1Ahmed1** [comment]
<img width="439" height="380" alt="Image" src="https://github.com/user-attachments/assets/815ed547-21f9-433d-8f55-509cd738b2b0" />

I had actually borrowed a Windows laptop to take the exam, but I later found a solution—as shown in the screenshot—which involves enabling the camera in the site settings before clicking "Launch Exam." I tested this using the "Test Your Device" feature and it worked; I was able to access the device test exam, even though the camera feed didn't actually appear in the bottom-right corner. I suggest you try accessing the device test exam as well; if it opens for you, I think that means everything is fine.

**Comment by 1Mohamed1Ahmed1** [comment]
@hagaralaa-55

**Comment by hagaralaa-55** [comment]
@1Mohamed1Ahmed1 , the test exam is working fine but without giving the option for camera , and when I tried to enter the exam , I had to enable the camera and stuck in this step , marked check box but the button for "start attempt " never enabled to be pressed

<img width="1200" height="1600" alt="Image" src="https://github.com/user-attachments/assets/5031f035-f2fd-402f-95cc-f738c8d07af8" />

**Comment by 1Mohamed1Ahmed1** [comment]
@hagaralaa-55 , This is so frustrating, i think ur final solution unfortunately is to borrow a Windows laptop as soon as u can.

**Comment by hagaralaa-55** [comment]
@1Mohamed1Ahmed1  yes u are right , I have to borrow a windows lap :) . I forgot to thank u for ur response, and good luck in ur next step.

**Comment by 1Mohamed1Ahmed1** [comment]
@hagaralaa-55  You're welcome, And GL with your exam

**Comment by karimelmasry42** [comment]
I am having the same problem, same specs, and my exam is right now and i don't have acess to a windows laptop as i am traveling :(
