### ISSUE TITLE
Config key failure (Hash being calculated on invalid JSON string)

### ISSUE THREAD

**Issue by harrisnl** [SafeExamBrowser/seb-mac#49]
Version: SEB MAC 2.1.4
Build: 2B66

After some days of trying to implement the SEB config key feature to my learning platform I came across a possible bug. I could not get the config key hash feature working, and after a long time testing, debugging and reading the log files I found out this:

The config key hash is being calculated on a invalid JSON string:
`{"hashedQuitPassword":"183297b53ba6bd201b3b9bc6d9e9ce5289ea7ed4a91f1516ec2c61802a6664ce","logLevel":4,`

It looks like the JSON string breaks down after the last comma.
Next SEB just calculates the config hash based on this invalid JSON string, check the log lines below.

2020/01/21 22:37:57:772  JSON for Config Key: {"hashedQuitPassword":"183297b53ba6bd201b3b9bc6d9e9ce5289ea7ed4a91f1516ec2c61802a6664ce","logLevel":4,
2020/01/21 22:37:57:772  Config Key: {length = 32, bytes = 0x76fed2a2 379dd1a3 d9538a26 de8053eb ... 26c3def0 ef68fe30 }

Is this a known bug or do I overlook something..?
Please let me know if any more debug information is needed.

**Comment by danschlet** [comment]
I would need to have the same settings you used to reproduce that. Did you generate those settings yourself or created and saved in SEB? Make sure that the value types for each key are correct (for example integers might be saved as strings for some settings).

I fixed some issues when calculating the Config Key, try it with the preview version of SEB 2.1.5: 
https://github.com/SafeExamBrowser/seb-testing/tree/master/mac/2.1.5

**Comment by harrisnl** [comment]
I generate my own SEB config file in my learning application.
See attachment
[7589.seb.txt](https://github.com/SafeExamBrowser/seb-mac/files/4097571/7589.seb.txt)

**Comment by danschlet** [comment]
Really weird that the 2.1.5 preview version isn't working for you on two different Macs, it works perfectly on 7 Macs with different systems and installations I tested it on...

Maybe I could find out what the problem is if you could send me the SEB log files, which are saved to the directory ~/Library/Logs/Safe Exam Browser/.

To reset wrong client settings, use use the command defaults delete org.safeexambrowser.Safe-Exam-Browser from the Terminal (see [the manual](https://safeexambrowser.org/macosx/mac_usermanual_en.html#ConfigDeployment) for such questions please).

**Comment by danschlet** [comment]
Ok, there is actually a bug in the current preview build (pre1) of SEB 2.1.5, which resets all setting keys, which are not contained in a loaded config file to wrong default values. That's why you can't quit 2.1.5 if you load your test settings.

I'll release a new build tomorrow or on Monday.

**Comment by harrisnl** [comment]
I just removed all settings with `defaults delete org.safeexambrowser.Safe-Exam-Browser`.
Still the same issue, even if I start SEB without my own configuration file.
I'll check the new build asap when available. Thanks!

**Comment by danschlet** [comment]
This is fixed in the currently available preview 2. Please retest. The final version of SEB 2.1.5 should be available in a few days.

**Comment by harrisnl** [comment]
@danschlet I can confirm that the latest build if 2.1.5 is indeed working correctly with the configuration hashing, Great work!

**Comment by gtbuchanan** [comment]
I can confirm 2.1.5pre2 resolves the issue for us as well. We're in the process of implementing SEB into our LMS and this was one of the blockers. Is 2.1.5 going to become the "official" release soon? I noticed it's available for download on the main site but most people are going to click the big blue button for 2.1.4.

**Comment by danschlet** [comment]
The official release is planed for next week.

**Comment by danschlet** [comment]
The Config Key issues were fixed in SEB 2.2.1 for macOS.
